# Generated by Django 3.2.23 on 2024-08-11 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('us_id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('us_nombres', models.CharField(max_length=100)),
                ('us_apellidos', models.CharField(max_length=100)),
                ('us_dni', models.CharField(max_length=10)),
                ('us_telefono', models.CharField(max_length=10)),
                ('us_zone', models.CharField(max_length=100)),
                ('us_pago_confirmado', models.BooleanField(default=False)),
                ('us_qrcode', models.ImageField(blank=True, null=True, upload_to='qr_codes/')),
            ],
        ),
    ]
