# Generated by Django 3.2.23 on 2024-08-22 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferencia_ng', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='us_imagen_pago',
            field=models.ImageField(blank=True, null=True, upload_to='payment_images/'),
        ),
    ]
